In [5]:
import pandas as pd

In [6]:
! ls Exo-Planet-Archive/PSCompPars_2022.12.02_18.47.14.csv

Crossmatching                         Pulsars
Exo-Planet-Archive                    README.md
Galaxy-Classification                 data-remapping.ipynb
Galaxy-Classification-Neural-Networks

In [17]:
data = pd.read_csv('./Exo-Planet-Archive/all_exoplanets_2021.csv')
data

,No.,Planet Name,Planet Host,Num Stars,Num Planets,Discovery Method,Discovery Year,Discovery Facility,Orbital Period Days,Orbit Semi-Major Axis,...,Equilibrium Temperature,Spectral Type,Stellar Effective Temperature,Stellar Radius,Stellar Mass,Stellar Metallicity,Stellar Metallicity Ratio,Stellar Surface Gravity,Distance,Gaia Magnitude
0,1,11 Com b,11 Com,2,1,Radial Velocity,2007,Xinglong Station,326.030000,1.290000,...,NaN,G8 III,4742.0,19.00,2.70,-0.350,[Fe/H],2.31,93.1846,4.44038
1,2,11 UMi b,11 UMi,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,516.219970,1.530000,...,NaN,NaN,4213.0,29.79,2.78,-0.020,[Fe/H],1.93,125.3210,4.56216
2,3,14 And b,14 And,1,1,Radial Velocity,2008,Okayama Astrophysical Observatory,185.840000,0.830000,...,NaN,K0 III,4813.0,11.00,2.20,-0.240,[Fe/H],2.63,75.4392,4.91781
3,4,14 Her b,14 Her,1,2,Radial Velocity,2002,W. M. Keck Observatory,1773.400020,2.930000,...,NaN,NaN,5338.0,0.93,0.90,0.410,[Fe/H],4.45,17.9323,6.38300
4,5,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996,Multiple Observatories,798.500000,1.660000,...,NaN,NaN,5750.0,1.13,1.08,0.060,[Fe/H],4.36,21.1397,6.06428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4570,4571,tau Gem b,tau Gem,1,1,Radial Velocity,2013,Lick Observatory,305.500000,1.170000,...,NaN,K2 III,4388.0,26.80,2.30,0.140,[Fe/H],1.96,112.5370,4.03996
4571,4572,ups And b,ups And,2,3,Radial Velocity,1996,Lick Observatory,4.617033,0.059222,...,NaN,F8 V,NaN,1.56,1.30,NaN,NaN,NaN,13.4054,3.98687
4572,4573,ups And c,ups And,2,3,Radial Velocity,1999,Multiple Observatories,241.258000,0.827774,...,NaN,F8 V,NaN,1.56,1.30,NaN,NaN,NaN,13.4054,3.98687
4573,4574,ups And d,ups And,2,3,Radial Velocity,1999,Multiple Observatories,1276.460000,2.513290,...,NaN,F8 V,NaN,1.56,1.30,NaN,NaN,NaN,13.4054,3.98687
4574,4575,xi Aql b,xi Aql,1,1,Radial Velocity,2007,Okayama Astrophysical Observatory,136.750000,0.680000,...,NaN,NaN,4780.0,12.00,2.20,-0.205,[Fe/H],2.66,56.1858,4.42501

In [22]:
data = pd.read_csv('./Exo-Planet-Archive/PS_data.csv',skiprows=49)
data.columns

Index(['pl_name', 'hostname', 'default_flag', 'sy_snum', 'sy_pnum',
       'discoverymethod', 'disc_year', 'disc_facility', 'soltype',
       'pl_controv_flag', 'pl_refname', 'pl_orbper', 'pl_orbsmax', 'pl_rade',
       'pl_radj', 'pl_bmasse', 'pl_bmassj', 'pl_bmassprov', 'pl_orbeccen',
       'pl_insol', 'pl_eqt', 'ttv_flag', 'st_refname', 'st_spectype',
       'st_teff', 'st_rad', 'st_mass', 'st_met', 'st_metratio', 'st_logg',
       'sy_refname', 'rastr', 'ra', 'decstr', 'dec', 'sy_dist', 'sy_vmag',
       'sy_kmag', 'sy_gaiamag', 'rowupdate', 'pl_pubdate', 'releasedate'],
      dtype='object')

In [24]:
nasaexo = pd.read_csv('./Exo-Planet-Archive/nasa_exoplanets.csv')
nasaexo

,row,name,light_years_from_earth,planet_mass,stellar_magnitude,discovery_date,planet_type,planet_radius,orbital_radius,orbital_period,eccentricity,solar_system_name,planet_discovery_method,planet_orbital_inclination,planet_density,right_ascension,declination,host_temperature,host_mass,host_radius
0,0,11 Comae Berenices b,305.0,19.4 Jupiters,4.740,2007,Gas Giant,1.08 x Jupiter,1.29 AU,326 days,0.23,11 Com,Radial Velocity,NaN,NaN,12h20m43.03s,+17d47m34.3s,4742.0,2.70,19.00
1,1,11 Ursae Minoris b,410.0,14.74 Jupiters,5.016,2009,Gas Giant,1.09 x Jupiter,1.53 AU,1.4 years,0.08,11 UMi,Radial Velocity,NaN,NaN,15h17m05.89s,+71d49m26.0s,4213.0,2.78,29.79
2,2,14 Andromedae b,247.0,4.8 Jupiters,5.227,2008,Gas Giant,1.15 x Jupiter,0.83 AU,185.8 days,0,14 And,Radial Velocity,NaN,NaN,23h31m17.42s,+39d14m10.3s,4813.0,2.20,11.00
3,3,14 Herculis b,59.0,4.66 Jupiters,6.610,2002,Gas Giant,1.15 x Jupiter,2.93 AU,4.9 years,0.37,14 Her,Radial Velocity,NaN,NaN,16h10m24.31s,+43d49m03.5s,5338.0,0.90,0.93
4,4,16 Cygni B b,69.0,1.78 Jupiters,6.250,1996,Gas Giant,1.2 x Jupiter,1.66 AU,2.2 years,0.68,16 Cyg B,Radial Velocity,NaN,NaN,19h41m51.97s,+50d31m03.1s,5750.0,1.08,1.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4279,4279,XO-6 b,773.0,4.4 Jupiters,10.250,2016,Gas Giant,2.07 x Jupiter,0.0815 AU,3.8 days,0,XO-6,Transit,86.00,0.62,06h19m10.39s,+73d49m39.7s,6720.0,1.47,1.93
4280,4280,XO-7 b,764.0,0.709 Jupiters,10.520,2019,Gas Giant,1.373 x Jupiter,0.04421 AU,2.9 days,0.04,XO-7,Transit,83.45,0.34,18h29m54.929s,+85d13m59.58s,6250.0,1.41,1.48
4281,4281,YZ Ceti b,12.0,0.75 Earths,12.074,2017,Terrestrial,0.93 x Earth,0.01557 AU,2 days,0,YZ Cet,Radial Velocity,NaN,NaN,01h12m30.64s,-16d59m56.3s,3056.0,0.13,0.17
4282,4282,YZ Ceti c,12.0,0.98 Earths,12.074,2017,Terrestrial,1.0 x Earth,0.0209 AU,3.1 days,0.04,YZ Cet,Radial Velocity,NaN,NaN,01h12m30.64s,-16d59m56.3s,3056.0,0.13,0.17
4283,4283,YZ Ceti d,12.0,1.14 Earths,12.074,2017,Super Earth,1.05 x Earth,0.02764 AU,4.7 days,0.13,YZ Cet,Radial Velocity,NaN,NaN,01h12m30.64s,-16d59m56.3s,3056.0,0.13,0.17